lio_optimization:
  ros__parameters:
    common:
      lidar_topic: "/velodyne_points"
      imu_topic: "/imu/data"
      wheel_topic: "/velocity"
      point_filter_num: 4
      sweep_cut_num: 1
      time_sync_en: false
      gravity_acc: [0.0, 0.0, 9.80416]
    
    lidar_parameter:
      lidar_type: 2  # 1: Livox, 2: Velodyne, 3: Ouster
      N_SCANS: 16
      SCAN_RATE: 10
      time_unit: 2  # 0: second, 1: millisecond, 2: microsecond, 3: nanosecond
      blind: 2.0
      fov_degree: 360.0
      det_range: 25.0

    imu_parameter:
      acc_cov: 0.1
      gyr_cov: 0.1
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      vel_cov: 0.1
      time_diff_enable: false

    extrinsic_parameter:
      extrinsic_enable: false
      extrinsic_t: [0.112, 0.176, -0.247]
      extrinsic_R: [
        1.0, 0.0, 0.0,
        0.0, 1.0, 0.0,
        0.0, 0.0, 1.0
      ]
      extrinsic_t_odom: [0.11, 0.18, 0.71]
      extrinsic_R_odom: [
        1.0, 0.0, 0.0,
        0.0, 1.0, 0.0,
        0.0, 0.0, 1.0
      ]

    odometry_options:
      voxel_size: 0.5
      sample_voxel_size: 1.5
      max_distance: 500.0
      max_num_points_in_voxel: 20
      method_system_init: 1  # STATIC_INIT
      init_num_frames: 20
      robust_registration: false
      min_distance_points: 0.15
      distance_error_threshold: 100.0
      motion_compensation: 3  # CONTINUOUS
      initialization: 2  # INIT_IMU

    icp_options:
      size_voxel_map: 1.0
      num_iters_icp: 15
      min_number_neighbors: 20
      voxel_neighborhood: 1
      max_number_neighbors: 20
      max_dist_to_plane_ct_icp: 0.3
      threshold_orientation_norm: 0.1
      threshold_translation_norm: 0.01
      debug_print: false
      point_to_plane_with_distortion: true
      distance: 1  # CT_POINT_TO_PLANE
      num_closest_neighbors: 1
      beta_location_consistency: 1.0
      beta_orientation_consistency: 1.0
      beta_constant_velocity: 1.0
      beta_small_velocity: 0.00
      solver: 0  # LIW
      min_num_residuals: 200
      max_num_residuals: 600
      loss_function: 2  # HUBER
      ls_max_num_iters: 5
      ls_num_threads: 16
      ls_sigma: 0.5
      ls_tolerant_min_threshold: 0.05